build:
  environment:
    php:
      version: 7.1

  tests:
    override:
      -
        command: vendor/bin/phpunit --coverage-clover clover.xml
        coverage:
          file: clover.xml
          format: php-clover